universe = vanilla
Executable     =  do_zhbb.sh
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
getenv = True
Notification     = never
#WhenToTransferOutput=Never
#requirements = OpSysAndVer == "CentOS7"
#request_cpus = 4
max_materialize = 5000
Output     = condor/log_$(Cluster)_$(Process).out
Error      = condor/log_$(Cluster)_$(Process).out
Log        = condor/log_$(Cluster)_$(Process).log
arguments = $(IN) $(OUT) $(PNAME)

queue IN, OUT, PNAME from modified_files.txt