universe = vanilla
Executable     =  do_vvhjj.sh
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
getenv = True
Notification     = never
#WhenToTransferOutput=Never
#requirements = OpSysAndVer == "CentOS7"
#request_cpus = 4
max_materialize = 5000
Output     = logs/log_$(Cluster)_$(Process).out
Error      = logs/log_$(Cluster)_$(Process).err
Log        = logs/log_$(Cluster)_$(Process).log
arguments = $(IN) $(OUT) $(PNAME)

queue IN, OUT, PNAME from inputs/bckg_inputs.txt
